config/routes.rb
Rails.application.routes.draw do
  resources :registers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "registers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/register.rb
class Register < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  def index
    @registers = Register.all
  end

  def new
    @register = Register.new
  end

  def edit
    set_register
  end

  def show
    set_register
  end

  def create
    @register = Register.new(register_params)
    respond_to do |format|
      if @register.save
        format.html { redirect_to registers_url, notice: "Registration complete! Your details are now saved." }
        format.json { render :index, status: :created, location: @register }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_register
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to registers_url, notice: "#{@register.first_name} #{@register.last_name}'s Registration details is updated." }
        format.json { render :index, status: :ok, location: @register }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_register
    @register.destroy!

    respond_to do |format|
      format.html { redirect_to registers_url, notice: "#{@register.first_name} #{@register.last_name}'s Registration deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_register
    @register = Register.find(params[:id])
  end

  def register_params
    params.require(:register).permit(:first_name, :last_name, :b_date, :gender, :email, :phone_num, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareRailsForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'fonts', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/registers/_form.html.erb
<%= form_with(model: register) do |form| %>
  <% if register.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(register.errors.count, "error") %> occured:</h2>

      <ul>
        <% register.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div>
      <%= form.label :first_name, style: "display: block" %>
      <%= form.text_field :first_name, required: true %>
    </div>
    <div>
      <%= form.label :last_name, style: "display: block" %>
      <%= form.text_field :last_name, required: true %>
    </div>
  </div>

  <div class="row">
    <div style="width: 100%;">
      <%= form.label :birth_date, style: "display: block;" %>
      <%= form.date_field :b_date, required: true, id: "register_birth_date", style: "width: 100%;" %>
    </div>
    <div style="min-width: 234px;">
      <%= form.label :gender, style: "display: block" %>
      <div class="radio-group">
            <%= form.label :gender_male, class: "container" do %>
                    <div>Male</div>                   
                    <%= form.radio_button :gender, 'Male', required: true, checked: true, id: "register_gender_male" %>
                    <span class="checkmark"></span>
            <% end %>
            <%= form.label :gender_female, class: "container" do %>
                    <div>Female</div>
                    <%= form.radio_button :gender, 'Female', id: "register_gender_female" %>
                    <span class="checkmark"></span>
            <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.email_field :email %>
    </div>
    <div>
      <%= form.label :phone_number, style: "display: block" %>
      <%= form.telephone_field :phone_num, pattern: "[0-9]{3,10}", required: true, id: "register_phone_number" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :subject, class: "form-label" %>
    <%= form.select :subject, options_for_select([["I don't know yet","I don't know yet"], ["Calculus I", "Calculus I"], ["Linear Algebra", "Linear Algebra"], ["Differential Equation", "Differential Equation"]], @register.subject), { prompt: "Choose option" }, class: "form-select", required: true %>
  </div>

  <div>
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/registers/_register.html.erb
<%# this is to display all data from @registers in controller %>
<div id="<%= dom_id register %>">
  <p>
    <strong>First name:</strong>
    <%= register.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= register.last_name %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= register.b_date %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= register.gender %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= register.email.empty? ? "-" : register.email%>
  </p>

  <p>
    <strong>Phone num:</strong>
    <%= register.phone_num %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= register.subject %>
  </p>

</div>

app/views/registers/edit.html.erb
<div class="main">
  <div class="edit-box">
    <h1>Editing register</h1>
    
    <%# render form with passing a registration record according to its :id %>
    <%= render "form", register: @register %>
    
    <br>
    
    <div>
      <%= link_to "Back to Home", registers_path, style: "text-decoration: underline;" %>
    </div>
  </div>
</div>

app/views/registers/index.html.erb
<div style="max-width: 1500px; margin: auto;">
  <p style="color: green"><%= notice %></p>
  
  <h1>Registers</h1>
  
  <%= link_to "New register", new_register_path, class: "reg-btn" %>
  <br><br>
  
  <div id="registers">
    <table>
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Birth date</th>
          <th>Gender</th>
          <th>Email</th>
          <th>Phone number</th>
          <th>Subject</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @registers.each do |register| %>
          <tr>
            <td><%= register.first_name %></td>
            <td><%= register.last_name %></td>
            <td><%= register.b_date %></td>
            <td><%= register.gender %></td>
            <td><%= register.email %></td>
            <td><%= register.phone_num %></td>
            <td><%= register.subject.empty? ? "-" : register.subject %></td>
            <td>
              <%= button_to "Edit", edit_register_path(register), method: :get, class: "edit-btn" %>
              <br>
              <%= button_to "Delete", register, method: :delete, class: "del-btn" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/registers/new.html.erb
<div class="main">
  <div class="register-form">
    <h1>Register Form</h1>
    <%= render "form", register: @register %>
    <br>
    <div>
      <%= link_to "Back to Home", registers_path, style: "text-decoration: underline;" %>
    </div>
  </div>
</div>